version: '3'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: l2F7J29g
      MYSQL_DATABASE: cmon_work_01
      MYSQL_USER: db_user
      MYSQL_PASSWORD: XqaNTCcJ
    volumes:
      - 'db-volume:/var/lib/mysql'
    ports:
      - '9906:3306'
    restart: always
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
    build:
      context: .
      dockerfile: db/Dockerfile
  web:
    depends_on:
      - db
    ports:
      - '80:80'
    restart: always
    stdin_open: true
    tty: true
    build:
      context: ../../../
      dockerfile: .wappler/targets/cmonWorkVer01/web/Dockerfile
volumes:
  db-volume: ~
